const physiotherapy = {
  // Canonical machine identity. The file/catalogue names retain the clinical
  // discipline term, but every build, runtime and provider contract publishes
  // the mission-ordered short identifier `physio`.
  id: 'physio',
  productName: 'AssessSuite Physiotherapy',
  shortName: 'AssessSuite Physio',
  practitionerNoun: 'Physiotherapist',
  practitionerNounPlural: 'Physiotherapists',
  practitionerShort: 'Physio',
  disciplineName: 'Physiotherapy',
  clinicalPromptRole: 'Registered Physiotherapist',
  releaseCountry: 'australia',
  lexicon: {
    client: 'patient',
    clientPlural: 'patients',
    clientTitleCase: 'Patient',
    clientPluralTitleCase: 'Patients',
    practitioner: 'physiotherapist',
    practitionerTitleCase: 'Physiotherapist',
    episode: 'episode of care',
    session: 'consultation',
    plan: 'management plan',
    planTitleCase: 'Management Plan',
    intervention: 'treatment',
    interventionTitleCase: 'Treatment',
    protocol: 'management protocol',
    protocolTitleCase: 'Management Protocol',
    protocolLibrary: 'Management Protocols',
    assessmentLibrary: 'Outcome Measures',
  },
  releaseProfessions: [
    'Physiotherapist',
    'Clinic Management',
  ],
  signup: {
    clinicalProfessionValue: 'Physiotherapist',
    clinicalProfessionLabel: 'Registered Physiotherapist (Ahpra)',
    managementRoles: ['Clinic Management'],
    registrationNumberLabel: 'Ahpra Registration Number',
    registrationNumberPlaceholder: 'e.g. PHY0001234567',
    registrationNumberRequired: true,
    qualificationsPlaceholder: 'e.g. Bachelor of Physiotherapy (Honours)',
    ineligibleMessage:
      'Self-service clinical accounts on this platform are limited to registered physiotherapists',
  },
  assessmentLibrary: {
    mode: 'explicit',
    seedFiles: ['physiotherapy-assessment-part'],
  },
  navigation: {
    primaryPages: [
      'Dashboard',
      'Calendar',
      'Clients',
      'PhysioEpisodes',
      'AssessmentLibrary',
      'TreatmentProtocols',
      'Reports',
      'FundingForms',
      'Finances',
      'Customise',
      'MyProfile',
    ],
    allowedPages: [
      'AdminAnalytics',
      'AdminApprovals',
      'AdminPromotions',
      'AssessmentLibrary',
      'Calendar',
      'ClientProfile',
      'Clients',
      'Customise',
      'Dashboard',
      'Finances',
      'FundingForms',
      'Home',
      'MyProfile',
      'NewAssessment',
      'NewAssessmentCreator',
      'Onboarding',
      'PendingApproval',
      'PhysioEpisodes',
      'ProfileSetup',
      'Reports',
      'TestRunner',
      'TreatmentProtocols',
      'UsageOverview',
    ],
  },
  reports: {
    allowedRegions: ['australia'],
    allowedTypeIds: [
      'physio_initial_assessment',
      'physio_progress_report',
      'physio_referrer_update',
      'physio_discharge_summary',
      'custom_report',
    ],
  },
  features: {
    careEpisodes: true,
    legacyGeneralClinicalLlm: true,
    aiTaskIds: [
      'physio.initial_assessment_summary.v1',
      'physio.soap_note.v1',
      'physio.management_plan.v1',
      'physio.progress_comparison.v1',
      'physio.referrer_update.v1',
      'physio.discharge_summary.v1',
    ],
    disabledCoreIntegrationIds: ['SendSMS', 'GenerateImage'],
  },
  branding: {
    accent: '#0d9488',
    accentDark: '#0f766e',
    logoAlt: 'AssessSuite Physiotherapy',
  },
  deployment: {
    shellId: 'app-physio',
    appId: 'local-assesssuite-physio',
    localAppPort: 4201,
    localServerPort: 8788,
    dataFile: 'physio.db',
    intendedAppHost: 'physio.app.assesssuite.com',
  },
};

export default physiotherapy;
