import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";

import {
  composeReportDraft,
  transitionReportLifecycle,
} from "../../src/lib/reports/core/reportCompositionEngine.js";
import {
  OUTCOME_TABLE_SLOT_HTML,
  buildLegacySavedReportPayload,
  createLegacyEditEnvelope,
  inspectLegacyRenderCompatibility,
  legacyPayloadFingerprint,
  recomposeLegacyReportHtml,
  reportHtmlFingerprint,
} from "../../src/lib/reports/core/legacyCompatibility.js";

const outcomeTable = [
  '<table class="outcome">',
  "<thead><tr><th>Assessment</th><th>Baseline</th><th>Most Recent</th><th>Change</th><th>Interpretation</th></tr></thead>",
  "<tbody><tr><td>Synthetic Measure</td><td>10</td><td>12</td><td>+2</td><td>Score increased</td></tr></tbody>",
  "</table>",
].join("");

const envelope = createLegacyEditEnvelope({
  documentPreambleHtml: '<!DOCTYPE html><html><head><style>.lh{color:#123}.outcome{width:100%}</style></head><body>',
  letterheadHtml: '<div class="lh"><h1>Synthetic Clinic</h1></div>',
  editableBodyHtml: `<section><h2>Outcome Measures</h2>${OUTCOME_TABLE_SLOT_HTML}<p>Synthetic original prose.</p></section>`,
  outcomeTableHtml: outcomeTable,
  signoffHtml: '<div class="signoff">Synthetic clinician</div>',
  footerHtml: '<div class="footer">Generated by AssessSuite</div>',
  documentPostambleHtml: "</body></html>",
});

function reportDraft() {
  const sectionBodies = {
    reason_for_report: "Synthetic reason.",
    treatment_summary: "Synthetic treatment summary.",
    outcome_measures: "Synthetic outcome summary.",
    current_status: "Synthetic status.",
    goal_progress: "Synthetic goal progress.",
    next_period_plan: "Synthetic next plan.",
  };
  return composeReportDraft({
    artifactId: "synthetic-compatibility-report",
    subject: { type: "client", id: "synthetic-client" },
    templateSelector: { templateKey: "general.progress-review.reporting-period.v1" },
    sourceCutoff: "2026-08-07T23:59:59.999+10:00",
    reportingPeriod: { start: "2026-08-01", end: "2026-08-07" },
    sources: [{
      sourceId: "synthetic-source",
      kind: "assessment_result",
      occurredAt: "2026-08-05",
      locator: { entity: "ClientAssessment", id: "synthetic-source" },
      contentDigest: "sha256:synthetic-source",
    }],
    sections: Object.entries(sectionBodies).map(([sectionKey, body]) => ({ sectionKey, body })),
    claims: [{
      claimId: "synthetic-claim",
      sectionKey: "outcome_measures",
      text: "Synthetic measure has a stored result.",
      sourceIds: ["synthetic-source"],
    }],
    generatedAt: "2026-08-08T00:30:00.000Z",
    createdBy: "synthetic-composer",
  });
}

function approvedReport() {
  const inReview = transitionReportLifecycle(reportDraft(), {
    to: "in_review",
    at: "2026-08-08T01:00:00.000Z",
    actorId: "synthetic-composer",
    reason: "Ready for synthetic review",
  });
  return transitionReportLifecycle(inReview, {
    to: "approved",
    at: "2026-08-08T02:00:00.000Z",
    actorId: "synthetic-reviewer",
    actorRole: "exercise_physiologist_reviewer",
    reason: "Synthetic fixture approved",
  });
}

function productionReleaseBinding(report, html, overrides = {}) {
  return {
    schemaVersion: "assesssuite.report-release-binding.v1",
    environment: "production",
    artifactId: report.artifactId,
    orgId: "synthetic-org",
    subjectType: report.subject.type,
    subjectId: report.subject.id,
    artifactState: "approved",
    artifactStateVersion: 2,
    authorActorId: report.version.createdBy,
    contentHash: "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    contentFingerprint: report.version.contentFingerprint,
    reportHtmlFingerprint: reportHtmlFingerprint(html),
    compatibilityVersion: "assesssuite.legacy-report-compatibility.v1",
    reviewId: "synthetic-review",
    reviewerActorId: "synthetic-reviewer",
    releaseAuthorizationEventId: "synthetic-release-event",
    releaseControllerActorId: "synthetic-release-controller",
    releaseControlComplete: true,
    releaseEligible: true,
    productionReleaseAuthority: true,
    ...overrides,
  };
}

test("rich editing can change prose without changing letterhead, outcome table, signoff, or footer", () => {
  const editedBody = `<section><h2>Outcome Measures</h2>${OUTCOME_TABLE_SLOT_HTML}<p>Synthetic revised prose.</p></section>`;
  const html = recomposeLegacyReportHtml(envelope, { editableBodyHtml: editedBody });
  const inspection = inspectLegacyRenderCompatibility(html, envelope);

  assert.equal(inspection.status, "compatible");
  assert.equal(inspection.blockerCount, 0);
  assert.ok(html.includes("Synthetic revised prose."));
  assert.ok(!html.includes("Synthetic original prose."));
  assert.ok(html.includes(envelope.letterheadHtml));
  assert.ok(html.includes(envelope.signoffHtml));
  assert.ok(html.includes(envelope.footerHtml));
  assert.equal(html.split(outcomeTable).length - 1, 1);
  assert.ok(html.includes("<div data-assess-body>"));
  assert.equal(
    reportHtmlFingerprint(html),
    `sha256:${createHash("sha256").update(html, "utf8").digest("hex")}`,
  );
});

test("compatibility inspection blocks a malformed outcome table", () => {
  const malformedEnvelope = createLegacyEditEnvelope({
    ...envelope,
    outcomeTableHtml: '<table class="outcome"><tr><td>not the established table</td></tr></table>',
  });
  const html = recomposeLegacyReportHtml(malformedEnvelope);
  const inspection = inspectLegacyRenderCompatibility(html, malformedEnvelope);
  assert.equal(inspection.status, "blocked");
  assert.ok(inspection.issues.some((item) => item.code === "OUTCOME_TABLE_SIGNATURE_INVALID"));
});

test("legacy SavedReport remains draft until exact production release evidence is bound", () => {
  const html = recomposeLegacyReportHtml(envelope);
  const draft = reportDraft();
  const draftPayload = buildLegacySavedReportPayload(draft, {
    entity: "SavedReport",
    clientId: "synthetic-client",
    orgId: "synthetic-org",
    reportHtml: html,
    editEnvelope: envelope,
    assessmentIds: ["synthetic-assessment-b", "synthetic-assessment-a", "synthetic-assessment-a"],
  });
  const lifecycleOnlyPayload = buildLegacySavedReportPayload(approvedReport(), {
    entity: "SavedReport",
    clientId: "synthetic-client",
    orgId: "synthetic-org",
    reportHtml: html,
    editEnvelope: envelope,
  });
  const finalPayload = buildLegacySavedReportPayload(draft, {
    entity: "SavedReport",
    clientId: "synthetic-client",
    orgId: "synthetic-org",
    reportHtml: html,
    editEnvelope: envelope,
    releaseBinding: productionReleaseBinding(draft, html),
  });

  assert.equal(draftPayload.status, "draft");
  assert.equal(lifecycleOnlyPayload.status, "draft");
  assert.equal(finalPayload.status, "final");
  assert.equal(draftPayload.report_html, html);
  assert.equal("html_content" in draftPayload, false);
  assert.deepEqual(draftPayload.assessment_ids, ["synthetic-assessment-a", "synthetic-assessment-b"]);
  assert.deepEqual(draftPayload.ai_assisted_sections, []);
  assert.equal(finalPayload.core_metadata.releaseEligible, true);
  assert.equal(finalPayload.core_metadata.lifecycleState, "approved");
  assert.equal(finalPayload.core_metadata.reportHtmlFingerprint, reportHtmlFingerprint(html));
  assert.deepEqual(finalPayload.core_metadata.subject, { type: "client", id: "synthetic-client" });
  assert.equal(finalPayload.core_metadata.releaseBinding.orgId, "synthetic-org");
  assert.equal(finalPayload.core_metadata.releaseBinding.subjectType, "client");
  assert.equal(finalPayload.core_metadata.releaseBinding.subjectId, "synthetic-client");
  assert.equal(finalPayload.core_metadata.releaseBinding.releaseControllerActorId, "synthetic-release-controller");
  assert.equal(finalPayload.core_metadata.releaseBinding.authorActorId, "synthetic-composer");
  assert.notEqual(
    finalPayload.core_metadata.releaseBinding.authorActorId,
    finalPayload.core_metadata.releaseBinding.reviewerActorId,
  );
  assert.equal(finalPayload.core_metadata.sourceManifest.schemaVersion, "assesssuite.source-manifest.v1");
  assert.equal(finalPayload.core_metadata.claimLedger.schemaVersion, "assesssuite.claim-ledger.v1");
  assert.equal(legacyPayloadFingerprint(finalPayload), legacyPayloadFingerprint(finalPayload));
});

test("sandbox, altered HTML, altered content, and incompatible renders can never map to final", () => {
  const report = reportDraft();
  const html = recomposeLegacyReportHtml(envelope);
  const base = {
    entity: "SavedReport",
    clientId: "synthetic-client",
    orgId: "synthetic-org",
    reportHtml: html,
    editEnvelope: envelope,
  };
  const sandbox = buildLegacySavedReportPayload(report, {
    ...base,
    releaseBinding: productionReleaseBinding(report, html, {
      environment: "sandbox",
      releaseEligible: false,
      productionReleaseAuthority: false,
    }),
  });
  assert.equal(sandbox.status, "draft");
  assert.ok(sandbox.core_metadata.releaseBlockers.includes("sandbox_or_unknown_environment"));

  const wrongAuthor = buildLegacySavedReportPayload(report, {
    ...base,
    releaseBinding: productionReleaseBinding(report, html, {
      authorActorId: "synthetic-substituted-author",
    }),
  });
  assert.equal(wrongAuthor.status, "draft");
  assert.ok(wrongAuthor.core_metadata.releaseBlockers.includes("author_actor_mismatch"));

  const missingAuthorBinding = productionReleaseBinding(report, html);
  delete missingAuthorBinding.authorActorId;
  const missingAuthor = buildLegacySavedReportPayload(report, {
    ...base,
    releaseBinding: missingAuthorBinding,
  });
  assert.equal(missingAuthor.status, "draft");
  assert.ok(missingAuthor.core_metadata.releaseBlockers.includes("release_evidence_incomplete"));

  const wrongTenant = buildLegacySavedReportPayload(report, {
    ...base,
    orgId: "synthetic-foreign-org",
    releaseBinding: productionReleaseBinding(report, html),
  });
  assert.equal(wrongTenant.status, "draft");
  assert.ok(wrongTenant.core_metadata.releaseBlockers.includes("tenant_binding_mismatch"));

  const wrongClient = buildLegacySavedReportPayload(report, {
    ...base,
    clientId: "synthetic-foreign-client",
    releaseBinding: productionReleaseBinding(report, html),
  });
  assert.equal(wrongClient.status, "draft");
  assert.ok(wrongClient.core_metadata.releaseBlockers.includes("report_subject_client_mismatch"));
  assert.ok(wrongClient.core_metadata.releaseBlockers.includes("client_binding_mismatch"));

  const wrongSubjectBinding = buildLegacySavedReportPayload(report, {
    ...base,
    releaseBinding: productionReleaseBinding(report, html, {
      subjectId: "synthetic-foreign-client",
    }),
  });
  assert.equal(wrongSubjectBinding.status, "draft");
  assert.ok(wrongSubjectBinding.core_metadata.releaseBlockers.includes("report_subject_binding_mismatch"));

  const missingTenantBinding = productionReleaseBinding(report, html);
  delete missingTenantBinding.orgId;
  const missingTenant = buildLegacySavedReportPayload(report, {
    ...base,
    releaseBinding: missingTenantBinding,
  });
  assert.equal(missingTenant.status, "draft");
  assert.ok(missingTenant.core_metadata.releaseBlockers.includes("release_evidence_incomplete"));

  const missingSubjectBinding = productionReleaseBinding(report, html);
  delete missingSubjectBinding.subjectType;
  const missingSubject = buildLegacySavedReportPayload(report, {
    ...base,
    releaseBinding: missingSubjectBinding,
  });
  assert.equal(missingSubject.status, "draft");
  assert.ok(missingSubject.core_metadata.releaseBlockers.includes("release_evidence_incomplete"));

  const changedHtml = html.replace("Synthetic original prose.", "Changed after release control.");
  const alteredRender = buildLegacySavedReportPayload(report, {
    ...base,
    reportHtml: changedHtml,
    releaseBinding: productionReleaseBinding(report, html),
  });
  assert.equal(alteredRender.status, "draft");
  assert.ok(alteredRender.core_metadata.releaseBlockers.includes("render_fingerprint_mismatch"));

  const alteredReport = {
    ...report,
    sections: report.sections.map((section, index) => (
      index === 0 ? { ...section, body: "Changed after approval." } : section
    )),
  };
  const alteredContent = buildLegacySavedReportPayload(alteredReport, {
    ...base,
    releaseBinding: productionReleaseBinding(report, html),
  });
  assert.equal(alteredContent.status, "draft");
  assert.ok(alteredContent.core_metadata.releaseBlockers.includes("report_fingerprint_invalid"));

  const incompatibleHtml = html.replace(envelope.footerHtml, "<div>footer changed</div>");
  const incompatible = buildLegacySavedReportPayload(report, {
    ...base,
    reportHtml: incompatibleHtml,
    releaseBinding: productionReleaseBinding(report, incompatibleHtml),
  });
  assert.equal(incompatible.status, "draft");
  assert.ok(incompatible.core_metadata.releaseBlockers.includes("legacy_render_incompatible"));
});

test("legacy ClientReport payload uses the historic html_content field", () => {
  const html = recomposeLegacyReportHtml(envelope);
  const payload = buildLegacySavedReportPayload(reportDraft(), {
    entity: "ClientReport",
    clientId: "synthetic-client",
    orgId: "synthetic-org",
    reportHtml: html,
  });

  assert.equal(payload.html_content, html);
  assert.equal("report_html" in payload, false);
  assert.equal(payload.report_type, "PROGRESS_NOTE");
});
