// Utility to check if an assessment has a dedicated interactive test runner
export const hasInteractiveRunner = (assessmentName) => {
  if (!assessmentName) return false;
  
  const name = assessmentName.toLowerCase();
  
  // List of all assessments with dedicated runners
  const interactiveRunners = [
    // Vital Signs
    () => name.includes('blood pressure'),
    () => name.includes('heart rate') && !name.includes('recovery'),
    () => name.includes('oxygen saturation') || name.includes('spo2'),
    
    // Functional Tests
    () => name.includes('hand grip') || name.includes('grip strength'),
    () => name === '6 minute walk test',
    () => name === '2-minute step test',
    () => name === 'single leg stance test (sls)' || name === 'single leg stance test' || name === 'one-leg stance test',
    () => name === 'y-balance test',
    () => name === '10-meter walk test (10mwt)',
    () => name === '4-stage balance test' || name.includes('4 stage balance') || name.includes('four stage balance'),
    () => name === 'habitual gait speed',
    () => name === 'fast gait speed',
    () => name === 'heart rate recovery',
    () => name === 'pain scales (vas/nprs)',
    
    // ROM and Strength
    () => name === 'range of motion (rom) assessment' || name === 'rom assessment' || name.includes('range of motion'),
    () => name.includes('manual muscle') || name === 'manual muscle testing (mmt)',
    
    // Body Composition
    () => name.includes('waist-hip') || name.includes('waist hip ratio') || name === 'waist-hip ratio',
    () => name.includes('body mass index') || name === 'bmi',
    () => name.includes('waist circumference') && !name.includes('hip'),
    () => name === 'height',
    () => name === 'weight',
    () => name.includes('skinfold') || name.includes('body fat percentage'),
    () => name.includes('girth measurement'),
    () => name.includes('dexa') || name.includes('dxa') || name.includes('dual-energy'),
    () => name.includes('bioelectrical impedance') || name.includes('bia'),
    () => name.includes('bod pod') || name.includes('air displacement'),
    () => name.includes('hydrostatic'),
    () => name.includes('body measurements'),
    () => name.includes('fasting blood glucose'),
    () => name.includes('oral glucose tolerance') || name.includes('ogtt'),
    
    // Balance Tests
    () => name.includes('berg balance'),
    () => name.includes('timed up and go') || name.includes('tug'),
    () => name.includes('chair stand') || name.includes('sit to stand') || name.includes('sit-to-stand'),
    () => name.includes('functional reach'),
    () => name.includes('back scratch'),
    () => name.includes('sit and reach') || name.includes('sit & reach'),
    () => name.includes('chair sit and reach'),
    () => name.includes('romberg'),
    () => name.includes('stork'),
    () => name.includes('standing stork'),
    () => name.includes('ctsib') || name.includes('sensory interaction'),
    () => name.includes('four square') || name.includes('4 square'),
    () => name.includes('community balance') || name.includes('cb&m'),
    () => name.includes('bestest') || name.includes('balance evaluation systems'),
    () => name.includes('elderly mobility scale') || name.includes('ems'),
    () => name.includes('pediatric balance'),
    () => name.includes('tandem stand') || name.includes('tandem balance'),
    () => name.includes('8 foot up') || name.includes('8-foot up'),
    () => name.includes('figure of eight') || name.includes('figure-of-eight'),
    () => name.includes('l test') || name.includes('l-test'),
    () => name.includes('hexagon agility'),
    () => name.includes('illinois agility'),
    () => name.includes('505 agility'),
    () => name.includes('t test') || name.includes('t-test agility'),
    () => name.includes('trendelenburg'),
    () => name.includes('dual task gait'),
    () => name.includes('functional gait assessment') || name.includes('fga'),
    () => name.includes('tuds'),
    () => name.includes('falls efficacy scale') && !name.includes('international'),
    () => name.includes('grocery shelving') || name.includes('gst'),
    () => name.includes('home step test'),
    () => name.includes('static squat') || name.includes('wall squat'),
    () => name.includes('plank hold'),
    () => name.includes('mcgill core') || name.includes('biering'),
    () => name.includes('static back extension'),
    () => name.includes('bruininks') || name.includes('bot-2'),
    
    // Cardio Tests
    () => name.includes('ebbeling') || name.includes('single-stage treadmill'),
    () => name.includes('iswt') || name.includes('incremental shuttle'),
    () => name.includes('harvard step'),
    () => name.includes('Ã¥strand') || name.includes('astrand'),
    () => name.includes('bruce'),
    () => name.includes('naughton'),
    () => name.includes('modified bruce'),
    () => name.includes('ymca cycle'),
    () => name.includes('wingate'),
    () => name.includes('2 minute walk') || name.includes('two minute walk'),
    () => name.includes('cooper') || name.includes('12 minute') || name.includes('12-minute'),
    () => name.includes('beep') || (name.includes('20') && name.includes('shuttle')),
    () => name.includes('yo-yo') || name.includes('yoyo'),
    () => name.includes('30-15') || name.includes('30 15'),
    () => name.includes('repeated sprint ability'),
    () => name.includes('vo2max testing') || name.includes('maximal graded exercise'),
    () => name.includes('ymca 3-minute') || name.includes('ymca 3 minute'),
    () => name.includes('rockport') || name.includes('1-mile walk'),
    () => name.includes('6-minute step') || name.includes('6 minute step'),
    () => name.includes('endurance shuttle') || name.includes('eswt'),
    () => name.includes('400 meter walk') || name.includes('400-meter walk'),
    () => name.includes('6 meter walk') || name.includes('6-meter walk'),
    () => name.includes('stair climb'),
    () => name.includes('chester step'),
    () => name.includes('step test') || name.includes('aerobic step'),
    () => name.includes('tecumseh'),
    () => name.includes('astrand-rhyming') || name.includes('astrand rhyming'),
    () => name.includes('tri-level arm') || name.includes('tri level arm'),
    () => name.includes('rmr') || name.includes('resting metabolic'),
    () => name.includes('forced vital capacity') || name.includes('fvc') || name.includes('spirometry'),
    () => name.includes('peak expiratory flow') || name.includes('pefr'),
    () => name.includes('copd assessment') || name.includes('cat'),
    () => name.includes('clinical copd') || name.includes('ccq'),
    () => name.includes('leicester cough') || name.includes('lcq'),
    () => name.includes('st george') || name.includes('sgrq'),
    () => name.includes('mrc dyspnea') || name.includes('mrc dyspnoea'),
    () => name.includes('borg dyspnea') || name.includes('borg dyspnoea'),
    () => name.includes('modified borg'),
    
    // Cognitive/Mental Health
    () => name.includes('moca') || name.includes('montreal cognitive'),
    () => name.includes('gad-7') || name.includes('gad7') || name.includes('generalized anxiety'),
    () => name.includes('phq-9') || name.includes('phq9') || name.includes('patient health questionnaire'),
    () => name.includes('k10') || name.includes('k-10') || name.includes('kessler'),
    () => name.includes('dass-21') || name.includes('dass21') || name.includes('dass 21') || name.includes('depression anxiety stress'),
    () => name.includes('acl return to sport') || name.includes('acl-rsi'),
    () => name.includes('fes-i') || (name.includes('falls efficacy') && name.includes('international')),
    () => name.includes('hads') || name.includes('hospital anxiety'),
    () => name.includes('impact of event') || name.includes('ies-r'),
    () => name.includes('ptsd checklist') || name.includes('pcl-5'),
    () => name.includes('insomnia severity') || name.includes('isi'),
    () => name.includes('perceived stress') || name.includes('pss'),
    () => name.includes('pittsburgh sleep') || name.includes('psqi'),
    () => name.includes('chalderc fatigue') || name.includes('cfs'),
    () => name.includes('fatigue severity') || name.includes('fss'),
    () => name.includes('promis fatigue'),
    () => name.includes('depaul symptom') || name.includes('dsq'),
    
    // Functional/Sport
    () => name.includes('box and block'),
    () => name.includes('himat') || name.includes('high-level mobility'),
    () => name.includes('job task analysis') || name.includes('icare'),
    () => name.includes('arm curl') || name.includes('bicep curl'),
    () => name.includes('hoos') || (name.includes('hip') && name.includes('osteoarthritis')),
    () => name.includes('koos') || (name.includes('knee') && name.includes('osteoarthritis') && name.includes('outcome')),
    () => name.includes('repeated jump') || name.includes('10-s repeated jump') || name.includes('10/5 repeated jump'),
    () => name.includes('ckcuest') || name.includes('closed kinetic chain upper'),
    () => name.includes('1rm') || name.includes('1-repetition maximum') || name.includes('one repetition maximum'),
    () => name.includes('isometric strength'),
    () => name.includes('isokinetic'),
    () => name.includes('lysholm'),
    () => name.includes('ikdc') || name.includes('international knee documentation'),
    () => name.includes('quick dash') || name.includes('quickdash'),
    () => name.includes('faam') || name.includes('foot and ankle ability'),
    () => name.includes('abc scale') || (name.includes('activities-specific') && name.includes('balance')),
    () => name.includes('womac'),
    () => name.includes('constant-murley') || name.includes('constant murley'),
    () => name.includes('lefs') || name.includes('lower extremity functional'),
    () => name.includes('neck disability') || name.includes('ndi'),
    () => name.includes('oswestry') || name.includes('odi'),
    () => name.includes('roland morris') || name.includes('rmdq'),
    () => name.includes('patient-specific functional') || name.includes('psfs'),
    () => name.includes('goal attainment') || name.includes('gas'),
    () => name.includes('fibromyalgia impact') || name.includes('fiq'),
    () => name.includes('widespread pain index') || name.includes('wpi'),
    () => name.includes('pain catastrophizing') || name.includes('pcs'),
    () => name.includes('fear avoidance') || name.includes('fabq'),
    () => name.includes('sf-36') || name.includes('sf36'),
    
    // Special Tests
    () => name.includes("ely's test") || name.includes("ely test"),
    () => name.includes("thomas test"),
    () => name.includes("ober's test") || name.includes("ober test"),
    () => name.includes('straight leg raise') || name.includes('slr'),
    () => name.includes('slump test'),
    () => name.includes('lachman'),
    () => name.includes('anterior drawer') && name.includes('knee'),
    () => name.includes('pivot shift'),
    () => name.includes('mcmurray'),
    () => name.includes('thessaly'),
    () => name.includes('apley'),
    () => name.includes('noble'),
    
    // Interpretation Tools
    () => name.includes('hba1c') || name.includes('glycated hemoglobin'),
    () => name.includes('lipid profile'),
    () => name.includes('met calculation') || name.includes('metabolic equivalent'),
    () => name.includes('global rating of change') || name.includes('groc'),
    () => name.includes('american shoulder and elbow surgeons') || name.includes('ases'),
    () => name.includes('clock drawing test'),
    
    // Other Performance Tests
    () => name.includes('physical performance test') || name.includes('ppt'),
    () => name.includes('borg') && name.includes('rpe'),
    () => name.includes('general movement screen'),
    () => name.includes('dynamic gait index') || name.includes('dgi'),
    () => name.includes('ten meter walk') || name.includes('10 meter walk') || name.includes('10-meter walk'),
    () => name.includes('barthelindex') || name.includes('barthel index'),
    () => name.includes('rivermead mobility'),
    () => name.includes('modified rankin'),
    () => name.includes('edss') || name.includes('expanded disability'),
    () => name.includes('fim') || name.includes('functional independence measure'),
    () => name.includes('motor assessment scale'),
    () => name.includes('modified ashworth'),
    () => name.includes('tardieu'),
    () => name.includes('functional ambulation'),
    () => name.includes('spinal cord independence') || name.includes('scim'),
    () => name.includes('clinical frailty'),
    () => name.includes('edmonton frail'),
    () => name.includes('sarcf') || name.includes('sarc-f'),
    () => name.includes('short physical performance') || name.includes('sppb'),
    () => name.includes('beighton'),
    () => name.includes('fms') || name.includes('functional movement screen'),
    () => name.includes('star excursion') || name.includes('sebt'),
    () => name.includes('drop vertical jump'),
    () => name.includes('single leg hop'),
    () => name.includes('triple hop'),
    () => name.includes('standing long jump'),
    () => name.includes('vertical jump') || name.includes('sargent'),
    () => name.includes('reactive strength'),
    () => name.includes('medicine ball throw'),
    () => name.includes('push up test') || name.includes('push-up test'),
    () => name.includes('maximal push up'),
    () => name.includes('timed push up'),
    () => name.includes('ymca bench press'),
    () => name.includes('step tap test'),
    () => name.includes('60 second sit') || name.includes('60-second sit'),
    () => name.includes('1 minute sit') || name.includes('1-minute sit'),
    () => name.includes('5 times sit') || name.includes('5x sts'),
    () => name.includes('digit span'),
    () => name.includes('trail making') || name.includes('tmt'),
    () => name.includes('stroop'),
    () => name.includes('grooved pegboard'),
    () => name.includes('purdue pegboard'),
    () => name.includes('nine hole peg') || name.includes('nine-hole peg') || name.includes('9 hole peg') || name.includes('9-hole peg'),
    () => name.includes('conley scale'),
    () => name.includes('fall risk assessment') || name.includes('frat'),
    () => name.includes('morse fall'),
    () => name.includes('tinetti') || name.includes('poma'),
  ];
  
  return interactiveRunners.some(check => check());
};