import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import test, { before, after } from 'node:test';
import { fileURLToPath } from 'node:url';

import {
  CAPABILITY_FLAGS,
  CAPABILITY_FLAG_NAMES,
  capabilityConfigured,
  capabilityEnabled,
  getFlag,
  selftestMockAllowed,
} from '../capabilityFlags.mjs';
import { assertParityAssuranceEnvironment, PARITY_ASSURANCE_UPLOADS_DIR } from '../productionBootstrap.mjs';
import { PARITY_ASSURANCE_DB_PATH } from '../db.mjs';
import {
  auditSources,
  buildManifest,
  discoverSurfaces,
  parseDotenvAssignments,
  parseForbiddenOpaqueOverrides,
  renderManifestJson,
  renderOperatorManifest,
  scanRawEnvironmentReads,
} from '../../scripts/flag-manifest.mjs';
// R10 reads the Fly configs through the test-owned copy of the
// parseReviewedFlyConfig algorithm rather than the checker's own parser, so
// the cross-check is not evaluated by the code it is auditing.
import { parseFlyEnv } from './support/fly-config.mjs';
import {
  activateUser,
  loginAdmin,
  registerUser,
  requestJson,
  startTestServer,
} from './support/server-harness.mjs';

const testsDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(testsDir, '..', '..');

const POSTURES = ['strict', 'implied-on', 'forced-off'];
const AMERICAN_SPELLINGS = /\b(behavior|authorize|authorization|organization|analyze|center|color)\b/i;

// WP3 hardening added a clinical-release gate to InvokeLLM: the bootstrap
// admin has no country/profession, so it is never clinically eligible (see
// src/lib/clinicalRelease.js). R00 characterises the flag/self-test-mock
// behaviour, which is independent of that gate, so it needs a provisioned,
// fully activated clinician instead of the plain admin token.
async function loginEligibleClinician(server) {
  const adminToken = await loginAdmin(server);
  const clinician = await registerUser(server, 'capability-flag-registry-clinician@example.test');
  await activateUser(server, adminToken, clinician.id);
  return clinician.token;
}

// R00 — characterisation. Written and confirmed GREEN on the unmodified
// tree (before server/capabilityFlags.mjs is wired into any call site) and
// re-run after each file in the Change 2 refactor moves. This is the safety
// net for the only behaviour-touching change in the flag-governance item: it
// pins the InvokeLLM disabled/enabled/self-test-mock behaviour and the
// public-settings transcription_enabled reporting that already exist today,
// so any refactor that silently changes one of the three SELFTEST/parity
// carve-outs is caught immediately rather than discovered later in a full
// assurance run.

test('R00 characterises pre-refactor InvokeLLM and transcription-reporting behaviour', async () => {
  // (a) The untested-anywhere-else carve-out: GENERAL_CLINICAL_LLM_ENABLED
  // unset, harness default SELFTEST=1 -> the self-test mock path (200).
  const unsetServer = await startTestServer();
  try {
    const admin = await loginEligibleClinician(unsetServer);
    const result = await requestJson(
      unsetServer,
      `/api/apps/${unsetServer.appId}/integration-endpoints/Core/InvokeLLM`,
      { method: 'POST', token: admin, body: { prompt: 'R00 unset+selftest characterisation' } },
    );
    assert.equal(result.status, 200, result.text);
    assert.equal(typeof result.body, 'string');
    assert.match(result.body, /placeholder narrative content generated by the local InvokeLLM mock/i);

    const publicSettings = await requestJson(
      unsetServer,
      `/api/apps/public/prod/public-settings/by-id/${unsetServer.appId}`,
    );
    assert.equal(publicSettings.status, 200, publicSettings.text);
    assert.equal(publicSettings.body?.public_settings?.transcription_enabled, false);
  } finally {
    await unsetServer.stop();
  }

  // (b) Explicit '0' -> 503, exact body. The `code` is P1's machine-readable
  // capability-withdrawal signal (server/capabilities.mjs's
  // CLINICAL_AI_DISABLED_CODE), not the generic 'internal_error' this
  // characterisation originally recorded; the error *message* is unchanged
  // and is the byte-identical string the flag registry documents.
  // server/tests/public-capabilities-contract.test.mjs C02 owns that code.
  const disabledServer = await startTestServer({ GENERAL_CLINICAL_LLM_ENABLED: '0' });
  try {
    const admin = await loginAdmin(disabledServer);
    const result = await requestJson(
      disabledServer,
      `/api/apps/${disabledServer.appId}/integration-endpoints/Core/InvokeLLM`,
      { method: 'POST', token: admin, body: { prompt: 'R00 disabled characterisation' } },
    );
    assert.equal(result.status, 503, result.text);
    assert.deepEqual(result.body, {
      code: 'ai_capability_disabled',
      error: 'General AI generation is disabled on this server.',
    });
  } finally {
    await disabledServer.stop();
  }

  // (c) '1' + LLM_REQUIRED='0' + no key -> 200 mock.
  const enabledServer = await startTestServer({
    GENERAL_CLINICAL_LLM_ENABLED: '1',
    LLM_REQUIRED: '0',
    OPENAI_API_KEY: '',
  });
  try {
    const admin = await loginEligibleClinician(enabledServer);
    const result = await requestJson(
      enabledServer,
      `/api/apps/${enabledServer.appId}/integration-endpoints/Core/InvokeLLM`,
      { method: 'POST', token: admin, body: { prompt: 'R00 enabled characterisation' } },
    );
    assert.equal(result.status, 200, result.text);
    assert.equal(typeof result.body, 'string');
    assert.match(result.body, /placeholder narrative content generated by the local InvokeLLM mock/i);
  } finally {
    await enabledServer.stop();
  }
});

test('R01 registry shape is complete and internally consistent', () => {
  assert.equal(CAPABILITY_FLAG_NAMES.length, 11);
  assert.equal(new Set(CAPABILITY_FLAG_NAMES).size, 11, 'flag names must be unique');
  const mandatoryKeys = [
    'name', 'kind', 'selftest', 'selftestMock', 'forcedOffUnder',
    'noticeRequired', 'capabilityReducing', 'reducesAvailabilityWhen',
    'owner', 'ownerName', 'ownerSummary', 'whenOff', 'values', 'serverGates',
    'reportedVia', 'clientDetector', 'detectorNote', 'clientSurfaces',
    'opaqueOverrideForbidden', 'overrideNote', 'caveats', 'documentedIn',
  ];
  for (const flag of CAPABILITY_FLAGS) {
    for (const key of mandatoryKeys) {
      assert.ok(Object.hasOwn(flag, key), `${flag.name} is missing "${key}"`);
    }
    assert.ok(POSTURES.includes(flag.selftest), `${flag.name}.selftest must be one of ${POSTURES.join('|')}`);
    assert.ok(['capability', 'posture'].includes(flag.kind));
    if (flag.clientDetector === null) {
      assert.ok(typeof flag.detectorNote === 'string' && flag.detectorNote.trim().length > 0, `${flag.name}: clientDetector is null but detectorNote is empty`);
    }
  }
});

test('R02 an unregistered name is fatal', () => {
  assert.throws(() => capabilityEnabled('NOT_A_FLAG', {}), /Unregistered runtime flag/);
  assert.throws(() => capabilityConfigured('NOT_A_FLAG', {}), /Unregistered runtime flag/);
  assert.throws(() => selftestMockAllowed('NOT_A_FLAG', {}), /Unregistered runtime flag/);
  assert.throws(() => getFlag('NOT_A_FLAG'), /Unregistered runtime flag/);
});

test('R03 resolver semantics over a cartesian environment sweep, one flag per posture', () => {
  const cases = [undefined, '', '0', '1', 'true'];
  const selftestValues = [undefined, '1'];
  const parityValues = [undefined, '1'];
  for (const [name, posture] of [
    ['LLM_REQUIRED', 'strict'],
    ['ALLOW_OPEN_REGISTRATION', 'implied-on'],
    ['OUTBOUND_EMAIL_ENABLED', 'forced-off'],
  ]) {
    for (const value of cases) {
      for (const selftest of selftestValues) {
        for (const parity of parityValues) {
          const environment = { [name]: value, SELFTEST: selftest, PARITY_ASSURANCE_MODE: parity };
          const enabled = capabilityEnabled(name, environment);
          const impliedOnBySelftest = posture === 'implied-on' && selftest === '1';
          if ((value === 'true' || value === '') && !impliedOnBySelftest) {
            assert.equal(enabled, false, `${name}=${JSON.stringify(value)} must never enable the switch itself (posture ${posture})`);
          }
          if (posture === 'forced-off' && (selftest === '1' || parity === '1')) {
            assert.equal(enabled, false, `${name} must be forced off under SELFTEST/PARITY_ASSURANCE_MODE`);
          }
        }
      }
    }
  }
});

test('R04 the self-test mock carve-out is exact and scoped to GENERAL_CLINICAL_LLM_ENABLED', () => {
  assert.equal(selftestMockAllowed('GENERAL_CLINICAL_LLM_ENABLED', { SELFTEST: '1' }), true);
  assert.equal(selftestMockAllowed('GENERAL_CLINICAL_LLM_ENABLED', { SELFTEST: '1', GENERAL_CLINICAL_LLM_ENABLED: '' }), false);
  assert.equal(selftestMockAllowed('GENERAL_CLINICAL_LLM_ENABLED', { GENERAL_CLINICAL_LLM_ENABLED: undefined }), false);
  for (const name of CAPABILITY_FLAG_NAMES) {
    if (name === 'GENERAL_CLINICAL_LLM_ENABLED') continue;
    assert.equal(selftestMockAllowed(name, { SELFTEST: '1' }), false, `${name} must not carry a self-test mock carve-out`);
  }
});

// R05 — the equivalence net. Each entry is a literal copy of the
// pre-refactor expression for that flag, held here (not derived from the
// registry) so this test would have caught Design 1's two selftest-fatal
// substitutions. Green the moment Change 1 lands; its job is to make the
// Change 2 call-site refactor provably safe.
const PRE_REFACTOR_ENABLED = new Map([
  ['ALLOW_OPEN_REGISTRATION', (e) => e.ALLOW_OPEN_REGISTRATION === '1' || e.SELFTEST === '1'],
  ['CORE_V1_SANDBOX_ENABLED', (e) => e.CORE_V1_SANDBOX_ENABLED === '1'],
  ['DOCUMENT_EXTRACTION_ENABLED', (e) => e.DOCUMENT_EXTRACTION_ENABLED === '1'],
  ['DOCUMENT_EXTRACTION_UNDER_13_ENABLED', (e) => e.DOCUMENT_EXTRACTION_UNDER_13_ENABLED === '1'],
  ['GENERAL_CLINICAL_LLM_ENABLED', (e) => e.GENERAL_CLINICAL_LLM_ENABLED === '1'],
  ['LLM_REQUIRED', (e) => e.LLM_REQUIRED === '1'],
  ['OUTBOUND_EMAIL_ENABLED', (e) => !(e.SELFTEST === '1' || e.PARITY_ASSURANCE_MODE === '1') && e.OUTBOUND_EMAIL_ENABLED === '1'],
  ['OUTBOUND_SMS_ENABLED', (e) => !(e.SELFTEST === '1' || e.PARITY_ASSURANCE_MODE === '1') && e.OUTBOUND_SMS_ENABLED === '1'],
  ['PAYMENTS_ENABLED', (e) => !(e.SELFTEST === '1' || e.PARITY_ASSURANCE_MODE === '1') && e.PAYMENTS_ENABLED === '1'],
  ['TRANSCRIPTION_ENABLED', (e) => e.TRANSCRIPTION_ENABLED === '1' || e.SELFTEST === '1'],
  ['UPLOAD_AUDIT_LEGAL_HOLD', (e) => e.UPLOAD_AUDIT_LEGAL_HOLD === '1'],
]);
const PRE_REFACTOR_CONFIGURED = new Map(CAPABILITY_FLAG_NAMES.map((name) => [name, (e) => e[name] === '1']));

test('R05 equivalence net — capabilityEnabled/capabilityConfigured match the literal pre-refactor expressions', () => {
  assert.equal(PRE_REFACTOR_ENABLED.size, 11);
  const cases = [undefined, '', '0', '1', 'true'];
  for (const name of CAPABILITY_FLAG_NAMES) {
    const expectedEnabled = PRE_REFACTOR_ENABLED.get(name);
    const expectedConfigured = PRE_REFACTOR_CONFIGURED.get(name);
    for (const value of cases) {
      for (const selftest of [undefined, '1']) {
        for (const parity of [undefined, '1']) {
          const environment = { [name]: value, SELFTEST: selftest, PARITY_ASSURANCE_MODE: parity };
          assert.equal(
            capabilityEnabled(name, environment),
            expectedEnabled(environment),
            `capabilityEnabled(${name}) drifted from the pre-refactor expression for ${JSON.stringify(environment)}`,
          );
          assert.equal(
            capabilityConfigured(name, environment),
            expectedConfigured(environment),
            `capabilityConfigured(${name}) drifted for ${JSON.stringify(environment)}`,
          );
        }
      }
    }
  }
});

const REGISTERED_NAMES_PATTERN = new RegExp(`^(?:${CAPABILITY_FLAG_NAMES.join('|')})$`);

function walkServerMjsFiles(root) {
  const entries = fs.readdirSync(root, { recursive: true, withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.mjs')) continue;
    const dir = entry.parentPath || entry.path || root;
    files.push(path.join(dir, entry.name));
  }
  return files;
}

test('R06 chokepoint scan — zero raw reads of a registered flag outside the registry', () => {
  const serverRoot = path.join(repoRoot, 'server');
  const offenders = [];
  for (const file of walkServerMjsFiles(serverRoot)) {
    const relPath = path.relative(repoRoot, file).split(path.sep).join('/');
    if (relPath.startsWith('server/tests/')) continue;
    if (relPath === 'server/capabilityFlags.mjs') continue;
    if (relPath === 'server/productionBootstrap.mjs') continue; // allowlisted data file, bound by R11
    const text = fs.readFileSync(file, 'utf8');
    for (const hit of scanRawEnvironmentReads(text)) {
      if (REGISTERED_NAMES_PATTERN.test(hit.name)) offenders.push(`${relPath}:${hit.line} (${hit.name})`);
    }
  }
  assert.deepEqual(offenders, []);
});

test('R07 unregistered-flag scan finds a synthetic capability-like name and ignores operational names', () => {
  const synthetic = [{
    file: 'server/synthetic-probe.mjs',
    text: [
      'export function probe(environment = process.env) {',
      "  if (process.env.FUTURE_THING_ENABLED === '1') return true;",
      "  if (process.env.SELFTEST === '1') return false;",
      "  if (process.env.OPENAI_HEALTH_DATA_TERMS_CONFIRMED === '1') return false;",
      '  return false;',
      '}',
    ].join('\n'),
  }];
  const findings = auditSources({
    registry: CAPABILITY_FLAGS,
    serverSources: synthetic,
    clientSources: {},
    configs: {},
    peerLists: {},
  });
  const unregistered = findings.filter((finding) => finding.kind === 'unregistered_capability');
  assert.equal(unregistered.length, 1);
  assert.equal(unregistered[0].name, 'FUTURE_THING_ENABLED');

  const cliResult = spawnSync(process.execPath, [path.join(repoRoot, 'scripts', 'flag-manifest.mjs'), 'check', '--json'], { cwd: repoRoot, encoding: 'utf8' });
  const parsed = JSON.parse(cliResult.stdout);
  assert.deepEqual(parsed.findings.filter((finding) => finding.kind === 'unregistered_capability'), []);
});

test('R08 manifest freshness and determinism', () => {
  const manifest = buildManifest({ repoRoot });
  const onDiskJson = fs
    .readFileSync(path.join(repoRoot, 'docs', 'deployment', 'flag-manifest.json'), 'utf8')
    .replaceAll('\r\n', '\n');
  assert.deepEqual(JSON.parse(renderManifestJson(manifest)), JSON.parse(onDiskJson));
  assert.equal(renderManifestJson(manifest), onDiskJson, 'Run: npm run flags:write');

  const onDiskMd = fs
    .readFileSync(path.join(repoRoot, 'docs', 'deployment', 'capability-manifest.md'), 'utf8')
    .replaceAll('\r\n', '\n');
  assert.equal(renderOperatorManifest(manifest, { repoRoot }), onDiskMd, 'Run: npm run flags:write');

  const manifestAgain = buildManifest({ repoRoot });
  assert.equal(renderManifestJson(manifest), renderManifestJson(manifestAgain));
  assert.equal(renderOperatorManifest(manifest, { repoRoot }), renderOperatorManifest(manifestAgain, { repoRoot }));
});

test('R09 client surface coverage is exact in both directions, and totals exactly 6 across 4 files', () => {
  const flag = getFlag('GENERAL_CLINICAL_LLM_ENABLED');
  const discovered = discoverSurfaces(flag.clientDetector, repoRoot);
  const discoveredPaths = new Set(discovered.map((surface) => surface.path));
  const declaredPaths = new Set(flag.clientSurfaces.map((surface) => surface.path));
  assert.deepEqual([...discoveredPaths].sort(), [...declaredPaths].sort());

  for (const surface of flag.clientSurfaces) {
    assert.ok(fs.existsSync(path.join(repoRoot, surface.path)), `${surface.path} does not exist`);
    assert.ok(surface.callSites >= 1, `${surface.path} must have at least one call site`);
  }
  for (const entry of flag.clientDetector.exclude) {
    assert.ok(entry.reason && entry.reason.trim().length > 0, `exclude entry for ${entry.path} has no reason`);
    assert.ok(fs.existsSync(path.join(repoRoot, entry.path)), `excluded path ${entry.path} does not exist`);
  }

  assert.equal(flag.clientSurfaces.length, 4);
  assert.equal(flag.clientSurfaces.reduce((sum, surface) => sum + surface.callSites, 0), 6);
});

test('R01b Core V1 sandbox exposure is strict, dormant and not implied by self-test', () => {
  const flag = getFlag('CORE_V1_SANDBOX_ENABLED');
  assert.equal(flag.selftest, 'strict');
  assert.equal(flag.selftestMock, null);
  assert.equal(flag.forcedOffUnder, null);
  assert.deepEqual(flag.values, {
    production: '0',
    rollback: '0',
    parity: '0',
    envExample: '',
  });
  assert.equal(capabilityEnabled('CORE_V1_SANDBOX_ENABLED', { SELFTEST: '1' }), false);
  assert.equal(capabilityEnabled('CORE_V1_SANDBOX_ENABLED', { SELFTEST: '1', CORE_V1_SANDBOX_ENABLED: '1' }), true);
  assert.equal(flag.clientDetector, null);
  assert.deepEqual(flag.clientSurfaces, []);
  assert.match(flag.serverGates[0].route, /\/api\/core\/v1\/\*/);
  assert.match(flag.serverGates[0].effectWhenOff, /production additionally hard-disables/i);
});

test('R10 deployment-file cross-check against fly.production.toml, fly.rollback.production.toml and .env.example', () => {
  const production = parseFlyEnv(fs.readFileSync(path.join(repoRoot, 'fly.production.toml'), 'utf8'));
  const rollback = parseFlyEnv(fs.readFileSync(path.join(repoRoot, 'fly.rollback.production.toml'), 'utf8'));
  const envExample = parseDotenvAssignments(fs.readFileSync(path.join(repoRoot, '.env.example'), 'utf8'));
  for (const flag of CAPABILITY_FLAGS) {
    const actualProduction = production.has(flag.name) ? production.get(flag.name) : null;
    const actualRollback = rollback.has(flag.name) ? rollback.get(flag.name) : null;
    const actualEnvExample = envExample.has(flag.name) ? envExample.get(flag.name) : null;
    assert.equal(flag.values.production, actualProduction, `${flag.name}.values.production`);
    assert.equal(flag.values.rollback, actualRollback, `${flag.name}.values.rollback`);
    assert.equal(flag.values.envExample, actualEnvExample, `${flag.name}.values.envExample`);
  }

  // Non-vacuity fixture: prove the comparator can actually fail.
  const mismatched = parseFlyEnv('[env]\nGENERAL_CLINICAL_LLM_ENABLED = "1"\n');
  assert.notEqual(getFlag('GENERAL_CLINICAL_LLM_ENABLED').values.production, mismatched.get('GENERAL_CLINICAL_LLM_ENABLED'));
});

test('R11 parity binding — the registry\'s values.parity drives assertParityAssuranceEnvironment without editing productionBootstrap.mjs', () => {
  const baseEnvironment = { PARITY_ASSURANCE_MODE: '1', ASSESSSUITE_DB_PATH: PARITY_ASSURANCE_DB_PATH, UPLOADS_DIR: PARITY_ASSURANCE_UPLOADS_DIR };
  for (const flag of CAPABILITY_FLAGS) {
    if (flag.values.parity !== null) baseEnvironment[flag.name] = flag.values.parity;
  }
  assert.doesNotThrow(() => assertParityAssuranceEnvironment(baseEnvironment));

  for (const flag of CAPABILITY_FLAGS) {
    if (flag.values.parity === null) continue;
    const mutated = { ...baseEnvironment, [flag.name]: flag.values.parity === '1' ? '0' : '1' };
    assert.throws(() => assertParityAssuranceEnvironment(mutated), new RegExp(`requires ${flag.name}=`));
  }
  for (const extra of ['ASSESSSUITE_DB_PATH', 'UPLOADS_DIR']) {
    const mutated = { ...baseEnvironment, [extra]: 'mutated-value' };
    assert.throws(() => assertParityAssuranceEnvironment(mutated), new RegExp(`requires ${extra}=`));
  }
});

test('R12 override cross-check with scripts/check-production-secrets.mjs, set equality both directions', () => {
  const secretsText = fs.readFileSync(path.join(repoRoot, 'scripts', 'check-production-secrets.mjs'), 'utf8');
  const forbidden = parseForbiddenOpaqueOverrides(secretsText);
  assert.ok(Array.isArray(forbidden) && forbidden.length > 0);
  const registryNames = new Set(CAPABILITY_FLAG_NAMES);
  const scriptSet = new Set(forbidden.filter((name) => registryNames.has(name)));
  const registrySet = new Set(CAPABILITY_FLAGS.filter((flag) => flag.opaqueOverrideForbidden).map((flag) => flag.name));
  assert.deepEqual([...scriptSet].sort(), [...registrySet].sort());
});

test('R12b capability notice audit is identical for LF and CRLF input', () => {
  const noticeLf = [
    '<!--capability-notice',
    'notice_id: 20260802-eol-parity',
    'date: 2026-08-02',
    'flags: GENERAL_CLINICAL_LLM_ENABLED',
    'direction: neutral',
    'release: test',
    'capability-notice-->',
    '',
    '## User-visible effect',
    'No effect.',
    '## Surfaces affected',
    'None.',
    '## Detection and monitoring',
    'Synthetic parser test.',
    '## Restoration criteria',
    'Not applicable.',
  ].join('\n');
  const run = (text) => auditSources({
    registry: CAPABILITY_FLAGS,
    serverSources: [],
    clientSources: {},
    configs: {},
    peerLists: {},
    notices: [{ name: '20260802-eol-parity.md', text }],
  }).filter((finding) => finding.kind.startsWith('notice_'));

  assert.deepEqual(run(noticeLf), []);
  assert.deepEqual(run(noticeLf.replaceAll('\n', '\r\n')), []);
  assert.ok(run('missing fence\r\n').some((finding) => finding.kind === 'notice_malformed'));
});

test('R13 operator page and every generated string use Australian English and are legible', () => {
  const manifestMd = fs.readFileSync(path.join(repoRoot, 'docs', 'deployment', 'capability-manifest.md'), 'utf8');
  assert.match(manifestMd, /## What a rollback would change today/);
  assert.match(manifestMd, /GENERAL_CLINICAL_LLM_ENABLED/);
  assert.match(manifestMd, /DOCUMENT_EXTRACTION_ENABLED/);
  assert.match(manifestMd, /General AI generation is disabled on this server\./);
  assert.match(manifestMd, /Self-test bypass/);
  assert.match(manifestMd, /dissect_to_soap/);

  const noticesDir = path.join(repoRoot, 'docs', 'deployment', 'notices');
  const noticeTexts = fs.readdirSync(noticesDir)
    .filter((name) => name.endsWith('.md') && name !== 'TEMPLATE.md')
    .map((name) => fs.readFileSync(path.join(noticesDir, name), 'utf8'));
  const prTemplate = fs.readFileSync(path.join(repoRoot, '.github', 'pull_request_template.md'), 'utf8');
  const corpus = [manifestMd, ...noticeTexts, prTemplate];

  assert.match(corpus.join('\n'), /\bauthorised\b/i);
  assert.match(corpus.join('\n'), /\brecognised\b/i);
  assert.match(corpus.join('\n'), /\bbehaviour\b/i);
  for (const text of corpus) {
    assert.equal(AMERICAN_SPELLINGS.test(text), false, `American spelling found in: ${text.slice(0, 60)}...`);
  }

  for (const flag of CAPABILITY_FLAGS) {
    for (const surface of flag.clientSurfaces) {
      assert.ok(surface.userVisibleWhenOff.length >= 30, `${flag.name}: ${surface.path} userVisibleWhenOff is too short`);
      assert.ok(surface.userVisibleWhenOff.endsWith('.'), `${flag.name}: ${surface.path} userVisibleWhenOff must end with a full stop`);
      assert.equal(AMERICAN_SPELLINGS.test(surface.userVisibleWhenOff), false);
    }
  }
});
